/**
 * types.ts — SessionKeyParts and SessionRecord interfaces (spec §3.1).
 *
 * AuditEntry / AuditLog are imported from @zia/callbacks — not re-declared
 * here (O4 resolved). This file owns only persistence-layer data shapes.
 */

/**
 * The three variable parts that make up a session key.
 * None may contain a colon — buildSessionKey() enforces this.
 */
export interface SessionKeyParts {
  platform: string;
  chatType: string;
  chatId: string;
}

/**
 * One row from the `sessions` table, mapped to camelCase TypeScript.
 * All fields correspond 1:1 to the SPEC-DDL-2 column definitions.
 */
export interface SessionRecord {
  /** UUID v4 — generated by buildSessionKey-caller / createSession */
  id: string;
  /** Canonical key: "agent:main:{platform}:{chat_type}:{chat_id}" */
  sessionKey: string;
  /** Originating gateway platform (e.g. "slack", "email", "tui") */
  sourcePlatform: string;
  /** JSON-serialized ModelConfig snapshot at session start */
  modelConfig: string;
  /** Cross-reference to pi.dev JSONL file — nullable */
  piSessionPath: string | null;
  /** ISO 8601 UTC timestamp */
  startedAt: string;
  /** ISO 8601 UTC; null while session is active */
  endedAt: string | null;
  /** Reason for closing: e.g. "graceful_shutdown", "timeout" */
  endReason: string | null;
  /** FK to parent sessions.id (no DB constraint for MVP) */
  parentSessionId: string | null;
}
